language: java

dist: trusty

jdk:
  - oraclejdk11

addons:
 sonarcloud:
    organization: unige-pinfo-2019

script:
  - mvn clean instal
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar