language: java

jdk:
  - oraclejdk11

addons:
 sonarcloud:
    organization: unige-pinfo-2019

script:
  - mvn clean install
  - mvn install -Ppackage-docker-image
  - mvn sonar:sonar -Dsonar.projectKey=unige-pinfo-2019_PInfo2 -Dsonar.organization=unige-pinfo-2019 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=6a52b61ec8bac75693325785b5dd8214362acae7

