language: java

dist: trusty

jdk:
  - oraclejdk11

addons:
 sonarcloud:
    organization: unige-pinfo-2019

script:
  - mvn clean install
  - mvn sonar:sonar -Dsonar.projectKey=unige-pinfo-2019_PInfo2 -Dsonar.organization=unige-pinfo-2019 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=85b6b47ed359fb35baabfb4bd697fda950e454eb