language: java

dist: trusty

jdk:
  - oraclejdk11

addons:
 sonarcloud:
    organization: unige-pinfo-2019
     token:
      secure: "$SONAR_TOKEN" 

script:
  - mvn clean install
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar